In [15]:
import pandas as pd
import datetime
from sklearn.preprocessing import StandardScaler
import numpy as np

In [16]:
excel_file="/home/jian/Projects/Saatva/MMM/URL_models/input/URL_SM_input_tabs_data_JL_2019-05-06.xlsx"
excel_file=pd.ExcelFile(excel_file)
excel_file.sheet_names

tab_list=[x for x in excel_file.sheet_names if "Stat" not in x]

In [17]:
df_data=excel_file.parse('Home Page')
df_ivs=df_data.copy()
df_ivs.drop(['date','trans_net','sales_net', 'Users', 'Sessions','ga:goal11Completions','Time on Page','Transactions'],axis=1,inplace=True)



# 1-Eigendecomposition - Computing Eigenvectors and Eigenvalues

In [18]:
X = df_ivs.values

X_std = StandardScaler().fit_transform(X)

/usr/local/lib/python3.6/site-packages/sklearn/utils/validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [19]:
# Covariance Matrix

mean_vec = np.mean(X_std, axis=0)
cov_mat = (X_std - mean_vec).T.dot((X_std - mean_vec)) / (X_std.shape[0]-1)
print('Covariance matrix \n%s' %cov_mat)

'''
print('NumPy covariance matrix: \n%s' %np.cov(X_std.T))
'''

Covariance matrix 
[[ 1.00274725 -0.23620138  0.38859808 ...,  0.12121055  0.42993815
  -0.05314379]
 [-0.23620138  1.00274725 -0.29564106 ..., -0.04398613 -0.22676353
   0.07837289]
 [ 0.38859808 -0.29564106  1.00274725 ...,  0.19742312  0.3452576
   0.01201136]
 ..., 
 [ 0.12121055 -0.04398613  0.19742312 ...,  1.00274725  0.38089581
   0.3679272 ]
 [ 0.42993815 -0.22676353  0.3452576  ...,  0.38089581  1.00274725
   0.00420581]
 [-0.05314379  0.07837289  0.01201136 ...,  0.3679272   0.00420581
   1.00274725]]


"\nprint('NumPy covariance matrix: \n%s' %np.cov(X_std.T))\n"

In [20]:
# Correlation Matrix

cov_mat = np.cov(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cov_mat)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

'''
cor_mat1 = np.corrcoef(X_std.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat1)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)

'''

'''
cor_mat2 = np.corrcoef(X.T)

eig_vals, eig_vecs = np.linalg.eig(cor_mat2)

print('Eigenvectors \n%s' %eig_vecs)
print('\nEigenvalues \n%s' %eig_vals)
'''

Eigenvectors 
[[ 0.21739511 -0.10820999  0.07719584 ...,  0.22336803  0.10912294
  -0.00510193]
 [-0.15265954  0.0756306  -0.04032876 ...,  0.11169865 -0.01951601
  -0.12019398]
 [ 0.25148831 -0.03014505  0.01080879 ..., -0.02807898 -0.17698752
  -0.02885343]
 ..., 
 [ 0.13927934  0.28234812  0.04719309 ..., -0.06126781  0.13292532
  -0.03384357]
 [ 0.21162419  0.05459559  0.14295751 ...,  0.15205248 -0.3780585
  -0.05721522]
 [ 0.02692331  0.13577939 -0.26271013 ..., -0.4528079   0.00116306
   0.35210388]]

Eigenvalues 
[ 7.8496294   7.35011869  4.27165865  2.75167208  1.80637368  1.50926279
  1.39543386  1.27271891  1.2440523   1.12969544  1.08797855  1.07628016
  0.98774847  0.9493792   0.02457303  0.9075104   0.86409209  0.08304159
  0.09364035  0.80363981  0.79045767  0.77442572  0.75796854  0.12588653
  0.13344621  0.15863984  0.17367984  0.7235117   0.70299153  0.67364597
  0.65386405  0.21711986  0.22453284  0.2350358   0.60538492  0.57622079
  0.56199458  0.53865967  0.2626388

"\ncor_mat2 = np.corrcoef(X.T)\n\neig_vals, eig_vecs = np.linalg.eig(cor_mat2)\n\nprint('Eigenvectors \n%s' %eig_vecs)\nprint('\nEigenvalues \n%s' %eig_vals)\n"

In [21]:
# Singular Vector Decomposition

u,s,v = np.linalg.svd(X_std.T)

# Unitary array(s)
u

array([[-0.21739511, -0.10820999,  0.07719584, ...,  0.07981907,
        -0.08797898,  0.02259331],
       [ 0.15265954,  0.0756306 , -0.04032876, ...,  0.02116832,
        -0.06101859,  0.0197878 ],
       [-0.25148831, -0.03014505,  0.01080879, ..., -0.04488925,
        -0.08859404,  0.00603682],
       ..., 
       [-0.13927934,  0.28234812,  0.04719309, ..., -0.4941514 ,
        -0.60932185, -0.08495439],
       [-0.21162419,  0.05459559,  0.14295751, ...,  0.07588005,
        -0.01039324, -0.02550683],
       [-0.02692331,  0.13577939, -0.26271013, ...,  0.1451977 ,
        -0.05084772,  0.01106731]])

# 2-Selecting Principal Components

In [22]:
for ev in eig_vecs:
    np.testing.assert_array_almost_equal(1.0, np.linalg.norm(ev))
print('Everything ok!')

Everything ok!


In [23]:
eig_vals

array([ 7.8496294 ,  7.35011869,  4.27165865,  2.75167208,  1.80637368,
        1.50926279,  1.39543386,  1.27271891,  1.2440523 ,  1.12969544,
        1.08797855,  1.07628016,  0.98774847,  0.9493792 ,  0.02457303,
        0.9075104 ,  0.86409209,  0.08304159,  0.09364035,  0.80363981,
        0.79045767,  0.77442572,  0.75796854,  0.12588653,  0.13344621,
        0.15863984,  0.17367984,  0.7235117 ,  0.70299153,  0.67364597,
        0.65386405,  0.21711986,  0.22453284,  0.2350358 ,  0.60538492,
        0.57622079,  0.56199458,  0.53865967,  0.26263884,  0.27088805,
        0.30457453,  0.50994941,  0.4836837 ,  0.4772613 ,  0.47116563,
        0.43534566,  0.4106257 ,  0.3912072 ,  0.3563519 ,  0.34197174,
        0.33848072])

In [24]:

# Make a list of (eigenvalue, eigenvector) tuples
eig_pairs = [(np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range(len(eig_vals))]

# Sort the (eigenvalue, eigenvector) tuples from high to low
eig_pairs.sort()
eig_pairs.reverse()

# Visually confirm that the list is correctly sorted by decreasing eigenvalues
print('Eigenvalues in descending order:')
for i in eig_pairs:
    print(i[0])

Eigenvalues in descending order:
7.84962939958
7.35011869084
4.27165864664
2.75167208047
1.80637368127
1.50926278755
1.39543386313
1.27271890704
1.24405230268
1.12969543762
1.08797854701
1.07628016387
0.98774847334
0.949379204114
0.907510399952
0.864092092853
0.803639812475
0.790457665691
0.774425721609
0.757968541106
0.723511695595
0.702991529736
0.673645968965
0.653864045114
0.605384919374
0.576220790498
0.561994581444
0.53865967224
0.509949406637
0.483683704727
0.477261301601
0.471165625778
0.43534566378
0.410625702555
0.391207200963
0.356351899096
0.341971737505
0.338480721924
0.30457452527
0.270888046755
0.262638835553
0.235035804326
0.224532838842
0.217119855489
0.173679843461
0.158639842715
0.133446208082
0.125886534192
0.093640348881
0.0830415872153
0.0245730329581


In [25]:
matrix_w = np.hstack((eig_pairs[0][1].reshape(51,1), 
                      eig_pairs[1][1].reshape(51,1),
                      eig_pairs[2][1].reshape(51,1),
                     eig_pairs[3][1].reshape(51,1),
                     eig_pairs[4][1].reshape(51,1),
                     eig_pairs[5][1].reshape(51,1),
                     eig_pairs[6][1].reshape(51,1),
                     eig_pairs[7][1].reshape(51,1),
                     eig_pairs[8][1].reshape(51,1),
                     eig_pairs[9][1].reshape(51,1),
                     eig_pairs[10][1].reshape(51,1),
                     eig_pairs[11][1].reshape(51,1)))

print('Matrix W:\n', matrix_w)

Matrix W:
 [[  2.17395107e-01  -1.08209989e-01   7.71958392e-02  -2.66068169e-01
    1.17565087e-01   4.62564969e-02   1.29584123e-03  -4.69541718e-02
   -4.29407788e-02  -2.59659166e-02   1.16336942e-01   6.17662439e-02]
 [ -1.52659544e-01   7.56306030e-02  -4.03287567e-02  -4.30687622e-02
    1.76086428e-01   2.74082455e-01   5.38443589e-02   1.63358378e-02
    7.54238974e-02   9.98311358e-02  -1.48188098e-01  -1.29790935e-01]
 [  2.51488310e-01  -3.01450465e-02   1.08087918e-02   5.23142298e-02
   -4.58505326e-02   2.57395896e-02  -8.10478407e-02  -1.46124999e-01
    1.25763923e-01  -2.64347532e-02  -2.02490939e-02   4.35137841e-02]
 [  4.49365721e-02   1.54923348e-01  -1.80590307e-01   2.09605446e-01
    2.29913109e-01   1.24772761e-01   7.45827090e-02  -2.37793708e-01
   -9.19385393e-02  -3.84860341e-02   7.22267591e-02   5.64709164e-02]
 [ -4.75782769e-02   2.97217729e-02   1.49714921e-01   1.25075872e-01
    2.01085516e-01  -1.56859611e-01  -2.21014084e-01  -2.81762887e-01
    1

# 3 - Projection Onto the New Feature Space

In [26]:
Y = X_std.dot(matrix_w)

In [27]:
Y

array([[  9.58119785e-01,  -6.07125134e+00,  -1.90410142e-01, ...,
         -8.17073111e-01,  -7.92736619e-01,   3.85784753e-01],
       [  1.44251530e+00,  -5.83282012e+00,  -7.81768250e-01, ...,
         -9.78774751e-01,  -9.21365555e-01,   8.92662236e-01],
       [  1.88676541e+00,  -6.07855566e+00,  -1.12493025e+00, ...,
         -1.10988128e+00,  -8.15910187e-01,   9.24228773e-01],
       ..., 
       [ -3.65032339e+00,  -1.04089687e+00,   3.99422420e+00, ...,
         -1.04689499e+00,   1.25717474e+00,  -1.32347809e+00],
       [ -1.90080291e+00,   5.16713145e-03,   3.24183011e+00, ...,
         -5.14236191e-01,   1.84481595e+00,  -1.46992172e+00],
       [ -3.79136064e+00,  -1.33516838e+00,   3.17089269e+00, ...,
         -1.13227841e+00,   2.08861767e+00,   1.73641965e-01]])

In [28]:
#################

In [29]:
DVs=df_data[['date','trans_net','Users','Sessions','ga:goal11Completions']]
DVs['Trans_Per_Usr']=DVs['trans_net']/DVs['Users']

# 0
df_cov_mat=pd.DataFrame(cov_mat)
df_cov_mat.index=df_ivs.columns.tolist()
df_cov_mat.columns=df_ivs.columns.tolist()

# 1
df_eigen_values=pd.DataFrame(columns={"component_count","eigenvalue"})
for i in range(len(eig_pairs)):
    df=pd.DataFrame({"component_count":i+1,"eigenvalue":eig_pairs[i][0]},index=[i])
    df_eigen_values=df_eigen_values.append(df)
# 2
df_X_std=pd.DataFrame(X_std)
df_X_std.columns=df_ivs.columns.tolist()
df_X_std.index=df_data['date']
df_X_std=df_X_std.reset_index()
# 3
matrics_weight=pd.DataFrame(matrix_w)
# 4
input_transformed=pd.DataFrame(Y)
input_transformed.index=df_data['date']
input_transformed.columns=["Component_"+str(x+1) for x in input_transformed.columns.tolist()]
input_transformed=input_transformed.reset_index()

input_transformed=pd.merge(input_transformed,DVs,on="date")

/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  


In [15]:
input_transformed.to_csv("/home/jian/Projects/Saatva/MMM/URL_models/input/PCA_HomePage_MMM_JL_"+str(datetime.datetime.now().date())+".csv",index=False)

writer=pd.ExcelWriter("/home/jian/Projects/Saatva/MMM/URL_models/input/PCA_HomePage_MMM_JL_"+str(datetime.datetime.now().date())+".xlsx",engine="xlsxwriter")
df_data.to_excel(writer,"HomePage_data",index=False)
df_cov_mat.to_excel(writer,"cov_mat",index=False)
df_eigen_values.to_excel(writer,"eigen_values",index=False)
df_X_std.to_excel(writer,"df_IVs_std",index=False)
matrics_weight.to_excel(writer,"matrics_weight",index=False)
input_transformed.to_excel(writer,"input_transformed",index=False)
writer.save()



# Use sklearn directly

In [30]:
from sklearn.decomposition import PCA as sklearnPCA
sklearn_pca = sklearnPCA(n_components=12)
Y_sklearn = sklearn_pca.fit_transform(X_std)

In [17]:
pd.DataFrame(Y_sklearn).shape

(365, 12)

In [18]:
DVs=df_data[['date','trans_net','Users','Sessions','ga:goal11Completions']]
DVs['Trans_Per_Usr']=DVs['trans_net']/DVs['Users']

df_data=df_data[['date']+[x for x in df_data.columns.tolist() if "www" in x]]
df_data=pd.merge(df_data,DVs,on="date")
df_data.to_csv("/home/jian/Projects/Saatva/MMM/URL_models/input/Original_HomePage_MMM_JL_"+str(datetime.datetime.now().date())+".csv",index=False)




/usr/local/lib/python3.6/site-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  
